# Generated by Django 4.2.7 on 2024-12-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='saved_amount',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_amount',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
